_target_: interdiff.models.PolicyNetwork
n_layer: 4
n_head: 4
n_embd: 384
dropout: 0.0
context_length: ${context.seq_len}
lm_head_out_size: 128
vocab_size: ${tokenizer.vocab_size}
bias: false
pad_token_id: ${tokenizer.pad_token_id}
bos_token_id: ${tokenizer.bos_token_id}
eos_token_id: ${tokenizer.eos_token_id}